export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_SUCCESS = "AUTH_SUCCES";
export const AUTH_RESULTS = "AUTH_RESULTS"
export const AUTH_FAILED = "AUTH_FAILED";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

export const REGISTER_DEVICE = "REGISTER_DEVICE"
export const RESULT_REGISTER_DEVICE = "RESULT_REGISTER_DEVICE";

export const CHECK_DEVICE = "CHECK_DEVICE"
export const RESULT_CHECK_DEVICE = "RESULT_CHECK_DEVICE"

export const DELETE_DEVICE = "DELETE_DEVICE"
export const RESULT_DELETE_DEVICE = "RESULT_DELETE_DEVICE"